
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmbox.h"

/*
 * The configuration table for devices
 */

XMbox_Config XMbox_ConfigTable[] =
{
	{
		 XPAR_MAILBOX_0_IF_0_DEVICE_ID, 
		 XPAR_MAILBOX_0_IF_0_BASEADDR, 
		 XPAR_MAILBOX_0_IF_0_USE_FSL,
		 XPAR_MAILBOX_0_IF_0_SEND_FSL,
		 XPAR_MAILBOX_0_IF_0_RECV_FSL
	},
	{
		 XPAR_MAILBOX_0_IF_1_DEVICE_ID, 
		 XPAR_MAILBOX_0_IF_1_BASEADDR, 
		 XPAR_MAILBOX_0_IF_1_USE_FSL,
		 XPAR_MAILBOX_0_IF_1_SEND_FSL,
		 XPAR_MAILBOX_0_IF_1_RECV_FSL
	},
};
