/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_1 */
#define XPAR_MICROBLAZE_1_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_1_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_1_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_1_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_1_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_1_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_1_BASE_VECTORS 0x00000000
#define XPAR_MICROBLAZE_1_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_1_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_1_DATA_SIZE 32
#define XPAR_MICROBLAZE_1_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_1_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_1_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_1_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_1_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_1_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_1_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_1_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_1_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_1_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_1_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_1_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_1_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_1_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_1_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_1_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_1_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_1_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_1_D_AXI 1
#define XPAR_MICROBLAZE_1_D_LMB 1
#define XPAR_MICROBLAZE_1_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_1_EDGE_IS_POSITIVE 0
#define XPAR_MICROBLAZE_1_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_1_ENDIANNESS 1
#define XPAR_MICROBLAZE_1_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_1_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_1_FREQ 100000000
#define XPAR_MICROBLAZE_1_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_1_FSL_LINKS 0
#define XPAR_MICROBLAZE_1_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_1_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_1_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_1_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_1_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_1_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_1_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_1_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_1_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_1_INTERCONNECT 2
#define XPAR_MICROBLAZE_1_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_1_I_AXI 0
#define XPAR_MICROBLAZE_1_I_LMB 1
#define XPAR_MICROBLAZE_1_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_1_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_1_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_1_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_1_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_1_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_1_MMU_ZONES 16
#define XPAR_MICROBLAZE_1_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_1_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_1_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_1_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_1_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_1_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_1_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_1_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_1_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_1_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_1_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_1_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_1_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_1_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_1_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_1_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_1_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_1_OPTIMIZATION 0
#define XPAR_MICROBLAZE_1_PC_WIDTH 32
#define XPAR_MICROBLAZE_1_PVR 0
#define XPAR_MICROBLAZE_1_PVR_USER1 0x00
#define XPAR_MICROBLAZE_1_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_1_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_1_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_1_SCO 0
#define XPAR_MICROBLAZE_1_TRACE 0
#define XPAR_MICROBLAZE_1_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_1_USE_BARREL 0
#define XPAR_MICROBLAZE_1_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_1_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_1_USE_DCACHE 0
#define XPAR_MICROBLAZE_1_USE_DIV 0
#define XPAR_MICROBLAZE_1_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_1_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_1_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_1_USE_FPU 0
#define XPAR_MICROBLAZE_1_USE_HW_MUL 0
#define XPAR_MICROBLAZE_1_USE_ICACHE 0
#define XPAR_MICROBLAZE_1_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_1_USE_MMU 0
#define XPAR_MICROBLAZE_1_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_1_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_1_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_1_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_1_COMPONENT_NAME design_1_microblaze_1_0
#define XPAR_MICROBLAZE_1_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_1_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_1_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_1_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 1
#define XPAR_MICROBLAZE_ID 1
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x00000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 0
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME design_1_microblaze_1_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 2

/* Definitions for peripheral MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x0001FFFF
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 1
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x0001FFFF
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_MICROBLAZE_1_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_0_WRITE_ACCESS 2
#define XPAR_BRAM_0_BASEADDR 0x00000000
#define XPAR_BRAM_0_HIGHADDR 0x0001FFFF

/* Canonical definitions for peripheral MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_MICROBLAZE_1_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32
#define XPAR_BRAM_1_ECC 0
#define XPAR_BRAM_1_FAULT_INJECT 0
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_1_WRITE_ACCESS 2
#define XPAR_BRAM_1_BASEADDR 0x00000000
#define XPAR_BRAM_1_HIGHADDR 0x0001FFFF


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x1FFFFFFF


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 2
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_1_AXI_INTC */
#define XPAR_MICROBLAZE_1_AXI_INTC_DEVICE_ID 0
#define XPAR_MICROBLAZE_1_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_1_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_MICROBLAZE_1_AXI_INTC_KIND_OF_INTR 0xFFFFFFFC
#define XPAR_MICROBLAZE_1_AXI_INTC_HAS_FAST 1
#define XPAR_MICROBLAZE_1_AXI_INTC_IVAR_RESET_VALUE 0x00000010
#define XPAR_MICROBLAZE_1_AXI_INTC_NUM_INTR_INPUTS 2


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_MICROBLAZE_1_AXI_INTC_DEVICE_ID
#define XPAR_MICROBLAZE_1_AXI_INTC_TYPE 0
#define XPAR_AXI_TIMER_1_INTERRUPT_MASK 0X000001
#define XPAR_MICROBLAZE_1_AXI_INTC_AXI_TIMER_1_INTERRUPT_INTR 0
#define XPAR_MAILBOX_0_INTERRUPT_1_MASK 0X000002
#define XPAR_MICROBLAZE_1_AXI_INTC_MAILBOX_0_INTERRUPT_1_INTR 1

/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_1_AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_MICROBLAZE_1_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000
#define XPAR_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFC
#define XPAR_INTC_0_HAS_FAST 1
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x00000010
#define XPAR_INTC_0_NUM_INTR_INPUTS 2
#define XPAR_INTC_0_INTC_TYPE 0

#define XPAR_INTC_0_TMRCTR_0_VEC_ID XPAR_MICROBLAZE_1_AXI_INTC_AXI_TIMER_1_INTERRUPT_INTR
#define XPAR_INTC_0_MBOX_0_VEC_ID XPAR_MICROBLAZE_1_AXI_INTC_MAILBOX_0_INTERRUPT_1_INTR

/******************************************************************/


/* Definitions for peripheral MAILBOX_0 IF 0 */
#define XPAR_MAILBOX_0_IF_0_DEVICE_ID 0
#define XPAR_MAILBOX_0_IF_0_BASEADDR 0x43600000
#define XPAR_MAILBOX_0_IF_0_USE_FSL 0
#define XPAR_MAILBOX_0_IF_0_SEND_FSL 0
#define XPAR_MAILBOX_0_IF_0_RECV_FSL 0

/* Definition for TestApp ID */
#define XPAR_MAILBOX_0_TESTAPP_ID 0

/* Definitions for peripheral MAILBOX_0 IF 1 */
#define XPAR_MAILBOX_0_IF_1_DEVICE_ID 1
#define XPAR_MAILBOX_0_IF_1_BASEADDR 0x43600000
#define XPAR_MAILBOX_0_IF_1_USE_FSL 0
#define XPAR_MAILBOX_0_IF_1_SEND_FSL 0
#define XPAR_MAILBOX_0_IF_1_RECV_FSL 0

/* Definitions for driver MAILBOX */
#define XPAR_XMBOX_NUM_INSTANCES 2

/******************************************************************/


/* Canonical definitions for peripheral MAILBOX_0 IF 0 */
#define XPAR_MBOX_0_DEVICE_ID XPAR_MAILBOX_0_IF_0_DEVICE_ID
#define XPAR_MBOX_0_BASEADDR 0x43600000
#define XPAR_MBOX_0_HIGHADDR 0x4360FFFF
#define XPAR_MBOX_0_USE_FSL XPAR_MAILBOX_0_IF_0_USE_FSL
#define XPAR_MBOX_0_SEND_FSL XPAR_MAILBOX_0_IF_0_SEND_FSL
#define XPAR_MBOX_0_RECV_FSL XPAR_MAILBOX_0_IF_0_RECV_FSL


/* Canonical definitions for peripheral MAILBOX_0 IF 1 */
#define XPAR_MBOX_1_DEVICE_ID XPAR_MAILBOX_0_IF_1_DEVICE_ID
#define XPAR_MBOX_1_BASEADDR 0x43600000
#define XPAR_MBOX_1_HIGHADDR 0x4360FFFF
#define XPAR_MBOX_1_USE_FSL XPAR_MAILBOX_0_IF_1_USE_FSL
#define XPAR_MBOX_1_SEND_FSL XPAR_MAILBOX_0_IF_1_SEND_FSL
#define XPAR_MBOX_1_RECV_FSL XPAR_MAILBOX_0_IF_1_RECV_FSL


/******************************************************************/


/* Definitions for peripheral MUTEX_0 IF 0 */
#define XPAR_MUTEX_0_IF_0_DEVICE_ID 0
#define XPAR_MUTEX_0_TESTAPP_ID 0
#define XPAR_MUTEX_0_IF_0_BASEADDR 0x43400000
#define XPAR_MUTEX_0_IF_0_NUM_MUTEX 16
#define XPAR_MUTEX_0_IF_0_ENABLE_USER 0

/* Definitions for peripheral MUTEX_0 IF 1 */
#define XPAR_MUTEX_0_IF_1_DEVICE_ID 1
#define XPAR_MUTEX_0_IF_1_BASEADDR 0x43400000
#define XPAR_MUTEX_0_IF_1_NUM_MUTEX 16
#define XPAR_MUTEX_0_IF_1_ENABLE_USER 0

/* Definitions for peripheral MUTEX_1 IF 0 */
#define XPAR_MUTEX_1_IF_0_DEVICE_ID 2
#define XPAR_MUTEX_1_TESTAPP_ID 2
#define XPAR_MUTEX_1_IF_0_BASEADDR 0x43410000
#define XPAR_MUTEX_1_IF_0_NUM_MUTEX 16
#define XPAR_MUTEX_1_IF_0_ENABLE_USER 0

/* Definitions for peripheral MUTEX_1 IF 1 */
#define XPAR_MUTEX_1_IF_1_DEVICE_ID 3
#define XPAR_MUTEX_1_IF_1_BASEADDR 0x43410000
#define XPAR_MUTEX_1_IF_1_NUM_MUTEX 16
#define XPAR_MUTEX_1_IF_1_ENABLE_USER 0

/* Definitions for peripheral MUTEX_2 IF 0 */
#define XPAR_MUTEX_2_IF_0_DEVICE_ID 4
#define XPAR_MUTEX_2_TESTAPP_ID 4
#define XPAR_MUTEX_2_IF_0_BASEADDR 0x43420000
#define XPAR_MUTEX_2_IF_0_NUM_MUTEX 16
#define XPAR_MUTEX_2_IF_0_ENABLE_USER 0

/* Definitions for peripheral MUTEX_2 IF 1 */
#define XPAR_MUTEX_2_IF_1_DEVICE_ID 5
#define XPAR_MUTEX_2_IF_1_BASEADDR 0x43420000
#define XPAR_MUTEX_2_IF_1_NUM_MUTEX 16
#define XPAR_MUTEX_2_IF_1_ENABLE_USER 0

/* Definitions for driver MUTEX */
#define XPAR_XMUTEX_NUM_INSTANCES 6

/******************************************************************/


/* Canonical definitions for peripheral MUTEX_1 IF 0 */
#define XPAR_MUTEX_0_DEVICE_ID XPAR_MUTEX_1_IF_0_DEVICE_ID
#define XPAR_MUTEX_0_BASEADDR 0x43410000
#define XPAR_MUTEX_0_HIGHADDR 0x4341FFFF
#define XPAR_MUTEX_0_NUM_MUTEX 16
#define XPAR_MUTEX_0_ENABLE_USER 0


/* Canonical definitions for peripheral MUTEX_1 IF 1 */
#define XPAR_MUTEX_0_DEVICE_ID XPAR_MUTEX_1_IF_1_DEVICE_ID
#define XPAR_MUTEX_0_BASEADDR 0x43410000
#define XPAR_MUTEX_0_HIGHADDR 0x4341FFFF
#define XPAR_MUTEX_0_NUM_MUTEX 16
#define XPAR_MUTEX_0_ENABLE_USER 0


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 50000000


/******************************************************************/

/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_1 */
#define XPAR_AXI_TIMER_1_DEVICE_ID 0
#define XPAR_AXI_TIMER_1_BASEADDR 0x41C00000
#define XPAR_AXI_TIMER_1_HIGHADDR 0x41C0FFFF
#define XPAR_AXI_TIMER_1_CLOCK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER_1 */
#define XPAR_TMRCTR_0_DEVICE_ID 0
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFF
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_1_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 50000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

