
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmutex.h"

/*
* The configuration table for devices
*/

XMutex_Config XMutex_ConfigTable[] =
{
	{
		 XPAR_MUTEX_0_IF_0_DEVICE_ID, 
		 XPAR_MUTEX_0_IF_0_BASEADDR, 
		 XPAR_MUTEX_0_IF_0_NUM_MUTEX, 
		 XPAR_MUTEX_0_IF_0_ENABLE_USER, 
	},
	{
		 XPAR_MUTEX_0_IF_1_DEVICE_ID, 
		 XPAR_MUTEX_0_IF_1_BASEADDR, 
		 XPAR_MUTEX_0_IF_1_NUM_MUTEX, 
		 XPAR_MUTEX_0_IF_1_ENABLE_USER, 
	},
	{
		 XPAR_MUTEX_1_IF_0_DEVICE_ID, 
		 XPAR_MUTEX_1_IF_0_BASEADDR, 
		 XPAR_MUTEX_1_IF_0_NUM_MUTEX, 
		 XPAR_MUTEX_1_IF_0_ENABLE_USER, 
	},
	{
		 XPAR_MUTEX_1_IF_1_DEVICE_ID, 
		 XPAR_MUTEX_1_IF_1_BASEADDR, 
		 XPAR_MUTEX_1_IF_1_NUM_MUTEX, 
		 XPAR_MUTEX_1_IF_1_ENABLE_USER, 
	},
	{
		 XPAR_MUTEX_2_IF_0_DEVICE_ID, 
		 XPAR_MUTEX_2_IF_0_BASEADDR, 
		 XPAR_MUTEX_2_IF_0_NUM_MUTEX, 
		 XPAR_MUTEX_2_IF_0_ENABLE_USER, 
	},
	{
		 XPAR_MUTEX_2_IF_1_DEVICE_ID, 
		 XPAR_MUTEX_2_IF_1_BASEADDR, 
		 XPAR_MUTEX_2_IF_1_NUM_MUTEX, 
		 XPAR_MUTEX_2_IF_1_ENABLE_USER, 
	},
};
