
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: XilKernel Configuration parameters
*
*******************************************************************/

#ifndef _CONFIG_INIT_H
#define _CONFIG_INIT_H



/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: LibXilKernel Initialization structures
*
*******************************************************************/

#include <sys/init.h>
#include <os_config.h>


#endif
