
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: XilKernel Configuration parameters
*
*******************************************************************/

#ifndef _OS_CONFIG_H
#define _OS_CONFIG_H


#define MB_XILKERNEL 

#define CONFIG_HARDWARE_EXCEPTIONS 

#define CONFIG_HARDWARE_EXCEPTIONS 

#define CONFIG_BASE_VECTORS 0x00000000

#define CONFIG_PTHREAD_SUPPORT true

#define MAX_PTHREADS 10

#define PTHREAD_STACK_SIZE 1000

#define CONFIG_PTHREAD_MUTEX true

#define MAX_PTHREAD_MUTEX 10

#define MAX_PTHREAD_MUTEX_WAITQ 10

#define CONFIG_TIMER_PIT true

#define SYSTMR_BASEADDR 0x41C00000

#define SYSTMR_INTERVAL 1000000

#define SYSTMR_CLK_FREQ 100000000

#define SYSTMR_CLK_FREQ_KHZ 100000

#define CONFIG_INTC true

#define SYSINTC_BASEADDR XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR

#define SYSINTC_DEVICE_ID XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID

#define SYSTMR_INTR_ID 0

#define SYSTMR_INTR_ID 0

#define SYSTMR_INTR_ID 0

#define CONFIG_SCHED true

#define SCHED_TYPE SCHED_PRIO

#define N_PRIO 32

#define CONFIG_PRIOSCHED true

#define MAX_READYQ 10

#define CONFIG_SEMA true

#define MAX_SEM 20

#define MAX_SEM_WAITQ 10

#define CONFIG_NAMED_SEMA true

#define CONFIG_MSGQ true

#define NUM_MSGQS 10

#define MSGQ_CAPACITY 10

#define CONFIG_ENHANCED_MSGQ true

#define USE_MALLOC true

#define CONFIG_TIME true

#define MAX_TMRS 10

#endif
